:icons: font
:icon-set: fa
:hardbreaks:
:imagesdir: img
:source-highlighter: pygments
:data-uri:
:!figure-caption:

= bpmn.pic

`bpmn.pic` is a collection of https://gitlab.com/aplevich/dpic[DPIC] macros for generating BPMN 2.0 diagram images for use in various kinds of documents and presentations.

Although the library focuses on supporting SVG as the primary output format, most of the elements (except pools and lanes) should also work with other formats produced by DPIC.

Currently supported BPMN element types include:

* **Events**: start, non-interrupting, catching, boundary, throwing, end;
* **Tasks**: none, receive, send, manual, service, user, script, rule;
* **Sub-Processes**: collapsed, sequential, parallel, loop, compensation, ad-hoc, expanded;
* **Gateways**: none, exclusive, parallel, inclusive, event-based (exclusive, parallel);
* **Flows**: sequence flow, default condition flow, conditional flow, message flow;
* **Pools**: horizontal pools and lanes, horizontal black box pools.

NOTE: The goal of `bpmn.pic` is to provide just the visual layer of BPMN 2.0. If you need full support for BPMN 2.0-compatible XML, please try other tools (like https://bpmn.io[bpmn.io]) instead.

== Resources

* https://gitlab.com/aplevich/dpic/-/blob/master/dpic-doc.pdf[DPIC documentation]

== Installation

Download `bpmn.pic` from https://gitlab.com/pkierat/bpmn-pic[here]:

----
$ wget https://gitlab.com/pkierat/bpmn-pic/-/raw/master/bpmn.pic
----

The file is self-contained, and has no external run-time dependencies apart from DPIC itself.

<<<

== Building from source

Buiding `bpmn.pic` requires the following tools to be available on the `PATH`:

* https://www.gnu.org/software/binutils/[Binutils]
* https://www.gnu.org/software/make/[Make]
* https://www.gnu.org/software/make/[M4 Macro Processor]

**Procedure**:

. Clone the repository from https://gitlab.com/pkierat/bpmn-dpic[GitLab] or https://gitlab.com/pkierat/bpmn-dpic[GitHub]:
+
----
$ git clone git@gitlab.com:pkierat/bpmn-pic.git ./bpmn-pic
$ cd bpmn-pic
----
+
. Build `bpmn.pic`:
+
----
$ make -C src clean all
----
+
. (Optional) Build `README.pdf`:
+
----
$ make README.pdf
----

== Usage

. Include the `bpmn.pic` file in your PIC diagram using the `copy` statement:
+
[source, pic]
----
.PS
copy "bpmn.pic"

Start(none); SequenceFlow(); Task("Task"); SequenceFlow(); End(none)
.PE
----
+
. Generate the SVG file:
+
----
$ dpic -v diagram.pic > diagram.svg
----

The output SVG should look like below:

image::diagram.svg[pdfwidth="20%", align="center"]

For more usage samples, please consult the `*.pic` files in the `img` directory.

<<<

== Elements

=== Events

`Start(type [, attributes ])`
`StartNonInterrupting(type [, attributes])`
`Boundary(type [, attributes])`
`BoundaryNonInterrupting(type [, attributes])`
`Catching(type [, attributes])`
`Throwing(type [, attributes])`
`End(type [, attributes])`

image::events.svg[pdfwidth="90%",align="center"]

<<<

=== Gateways

`Gateway(type [, attributes ])`

image::gateways.svg[pdfwidth="90%",align="center"]

=== Activities

==== Tasks

`Task(text [, type [, attributes ] ])`

image::tasks.svg[pdfwidth="90%",align="center"]

==== Sub-processes

`SubProcess(text [, type [, attributes ] ])`

image::sub-processes.svg[pdfwidth="90%",align="center"]

=== Flows

`SequenceFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`DefaultFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`ConditionalFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`MessageFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`

image::flows.svg[pdfwidth="90%",align="center"]

=== Pools and Lanes

`Pool(width, height, lanes [, attributes ])`
`BlackBoxPool(width, height [, attributes ])`
`Lane(height, process [, attributes ])`

image::pools.svg[pdfwidth="90%",align="center"]

=== Text

`Text(text, position [, rotation ])`

image::text.svg[pdfwidth="50%",align="center"]

<<<

== Demo

image::demo.svg[pdfwidth="90%",align="center"]

== Notes

. `bpmn.pic` doesn't perform any kind of syntactic or semantic validation against the BPMN 2.0 spec. In particular, there's no check if a given combination of event type (start, end etc.) and trigger type (message, timer etc.) is valid according to the specification.
. DPIC does not support text rotation, it needs to be implemented in SVG directly instead. For the rotated text to render properly, it must be created after its target location is determined, e.g.:
+
[source, pic]
----
.PS
B: box width 0.25 height 1 ; { Text("Rotated text", B.c, "-90") }
.PE
----
+
Also, for the same reason, the north-west corner of the entire diagram needs to be positioned at (0, 0). This can be achieved by positioning the first element with .nw at (0, 0) or by using the dedicated `Diagram(width [, title ])` macro:
+
[source, pic]
----
.PS
Diagram(10, "Diagram")
P: Pool(10, 1, []) ; { Text("Pool", P.Label.c, -90) }
.PE
----
