:icons: font
:icon-set: fa
:hardbreaks:
:imagesdir: img
:source-highlighter: pygments
:data-uri:
:!figure-caption:

= bpmn.pic

`bpmn.pic` is a collection of https://gitlab.com/aplevich/dpic[DPIC] macros for generating BPMN 2.0 diagrams (as images) for use in various kinds of documents and presentations. Although the library focuses on supporting SVG as the primary output format, most of the elements (except pools and lanes) should also work with other DPIC formats.

Currently supported BPMN element types include:

* **Events**: start, non-interrupting, catching, boundary, throwing, end;
* **Tasks**: none, receive, send, manual, service, user, script, rule;
* **Sub-Processes**: collapsed, expanded;
* **Gateways**: none, exclusive, parallel, inclusive, event-based (exclusive, parallel);
* **Flows**: sequence flow, default condition flow, conditional flow, message flow;
* **Pools**: horizontal pools and lanes, horizontal black box pools.

NOTE: The goal of `bpmn.pic` is to provide just the visual layer of BPMN 2.0. If you need full support for BPMN 2.0-compatible XML, please try other tools (like https://bpmn.io[bpmn.io]) instead.

== Installation

Download `bpmn.pic` from https://gitlab.com/pkierat/bpmn-pic[GitLab]:

----
$ wget https://gitlab.com/pkierat/bpmn-pic/-/raw/master/bpmn.pic
----

The file is self-contained, and has no external run-time dependencies apart from DPIC itself.

== Building from source

Buiding `bpmn.pic` requires the following tools to be available on the `PATH`:

* https://www.gnu.org/software/binutils/[Binutils]
* https://www.gnu.org/software/make/[Make]
* https://www.gnu.org/software/make/[M4 Macro Processor]

Building `README.pdf` requires in addition:

* DPIC
* Asciidoctor PDF
* Asciidoctor Diagram

**Procedure**:

. Clone the repository:
+
----
$ git clone git@gitlab.com:pkierat/bpmn-pic.git ./bpmn-pic
$ cd bpmn-pic
----
+
. Build `bpmn.pic`:
+
----
$ make -C src bpmn.pic
----
+
. (Optional) Build `README.pdf`:
+
----
$ make README.pdf
----

== Usage

. Include the `bpmn.pic` file in your PIC diagram using the `copy` statement:
+
[source, pic]
----
.PS
copy "bpmn.pic"

Start(none); SequenceFlow(); Task("Task"); SequenceFlow(); End(none)
.PE
----
+
. Generate the SVG file:
+
----
$ dpic -v diagram.pic > diagram.svg
----

<<<

== Macros

=== Events

`Start(type [, attributes ])`
`StartNonInterrupting(type [, attributes])`
`Boundary(type [, attributes])`
`BoundaryNonInterrupting(type [, attributes])`
`Catching(type [, attributes])`
`Throwing(type [, attributes])`
`End(type [, attributes])`

=== Gateways

`Gateway(type [, attributes ])`

=== Activities

`Task(text [, type [, attributes ] ])`
`SubProcess(text [, type [, attributes ] ])`

=== Flows

`SequenceFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`DefaultFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`ConditionalFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`MessageFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`

=== Pools and lanes

`HorizontalPool(width, height, lanes [, attributes ])`
`HorizontalBlackBoxPool(width, height [, text [, attributes ] ])`
`HorizontalLane(height, process [, attributes ])`
`Pool(width, height, lanes [, attributes ])`
`Lane(height, process [, attributes ])`

=== Other

`Text(text, position [, rotation ])`

<<<

== Elements

=== Events

[%header,grid="none",frame="none"]
|===
| Start | Non-int. | Catching | Boundary non-int. | Throwing | End
|===

[dpic,events,pdfwidth="100%",align="center"]
----
copy "bpmn.pic"

E0: Start(none); move right 1
    move right 4.2
    Throwing(none); move right 1
    End(none); move right 1

move to (E0.w.x, E0.s.y - 0.5)

E1: Start(message); move right 1
    StartNonInterrupting(message); move right 1
    Catching(message); move right 1
    BoundaryNonInterrupting(message); move right 1
    Throwing(message); move right 1
    End(message); move right 1

move to (E1.w.x, E1.s.y - 0.5)

E2: Start(timer); move right 1
    StartNonInterrupting(timer); move right 1
    Catching(timer); move right 1
    BoundaryNonInterrupting(timer); move right 1
    Throwing(timer); move right 1
    End(timer); move right 1

move to (E2.w.x, E2.s.y - 0.5)

E3: Start(signal); move right 1
    StartNonInterrupting(signal); move right 1
    Catching(signal); move right 1
    BoundaryNonInterrupting(signal); move right 1
    Throwing(signal); move right 1
    End(signal); move right 1

move to (E3.w.x, E3.s.y - 0.5)

E4: Start(multiple); move right 1
    StartNonInterrupting(multiple); move right 1
    Catching( multiple); move right 1
    BoundaryNonInterrupting(multiple); move right 1
    Throwing(multiple); move right 1
    End(multiple); move right 1

move to (E4.w.x, E4.s.y - 0.5)

E5: Start(conditional); move right 1
    StartNonInterrupting(conditional); move right 1
    Catching(conditional); move right 1
    BoundaryNonInterrupting(conditional); move right 1
    Throwing(conditional); move right 1
    End(conditional); move right 1

move to (E5.w.x, E5.s.y - 0.5)

E6: Start(link); move right 1
    StartNonInterrupting(link); move right 1
    Catching(link); move right 1
    BoundaryNonInterrupting(link); move right 1
    Throwing(link); move right 1
    End(link); move right 1

move to (E6.w.x, E6.s.y - 0.5)

E7: Start(escalation); move right 1
    StartNonInterrupting(escalation); move right 1
    Catching(escalation); move right 1
    BoundaryNonInterrupting(escalation); move right 1
    Throwing(escalation); move right 1
    End(escalation); move right 1

move to (E7.w.x, E7.s.y - 0.5)

E8: Start(error); move right 1
    StartNonInterrupting(error); move right 1
    Catching(error); move right 1
    BoundaryNonInterrupting(error); move right 1
    Throwing(error); move right 1
    End(error); move right 1

move to (E8.w.x, E8.s.y - 0.5)

E9: Start(cancel); move right 1
    StartNonInterrupting(cancel); move right 1
    Catching(cancel); move right 1
    BoundaryNonInterrupting(cancel); move right 1
    Throwing(cancel); move right 1
    End(cancel); move right 1

move to (E9.w.x, E9.s.y - 0.5)

E10: Start(parallel); move right 1
     StartNonInterrupting(parallel); move right 1
     Catching(parallel); move right 1
     BoundaryNonInterrupting(parallel); move right 1
     Throwing(parallel); move right 1
     End(parallel); move right 1

move to (E10.w.x, E10.s.y - 0.5)

E11: Start(compensation); move right 1
     StartNonInterrupting(compensation); move right 1
     Catching(compensation); move right 1
     BoundaryNonInterrupting(compensation); move right 1
     Throwing(compensation); move right 1
     End(compensation); move right 1

move to (E11.w.x, E11.s.y - 0.5)

E12: Start(terminate); move right 1
     StartNonInterrupting(terminate); move right 1
     Catching(terminate); move right 1
     BoundaryNonInterrupting(terminate); move right 1
     Throwing(terminate); move right 1
     End(terminate); move right 1

move to (E12.w.x, E12.s.y - 0.5)
----

<<<

=== Gateways

[dpic,gateways,pdfwidth="90%",align="center"]
----
copy "bpmn.pic"

Gateway(none); move right;
Gateway(exclusive); move right;
Gateway(parallel); move right;
Gateway(inclusive); move right;
Gateway(complex); move right;
Gateway(event_based); move right;
Gateway(event_based_exclusive); move right;
Gateway(event_based_parallel); move right;
----

=== Activities

==== Tasks

[dpic,tasks,pdfwidth="90%",align="center"]
----
copy "bpmn.pic"

T1: Task("Task", none); move right;
T2: Task("Send task", send); move right;
T3: Task("Receive task", receive); move right;
T4: Task("Manual task", manual)

move to T1.sw + (0, -0.5)

T5: Task("Service task", service) move right;
T6: Task("User task", user); move right;
T7: Task("Script task", script); move right;
T8: Task("Business" "Rule task", rule)

----

==== Sub-processes

[dpic,sub-processes]
----
copy "bpmn.pic"

P1: SubProcess("Collapsed" "Sub-Process", collapsed)
----

==== Flows

[dpic,flows,pdfwidth="90%",align="center"]
----
copy "bpmn.pic"

SequenceFlow(right 2); L: last line; { "Sequence flow" at L.c + (0, 0.1) }
move
DefaultFlow(right 2); L: last line; { "Default flow" at L.c + (0, 0.1) }
move
ConditionalFlow(right 2); L: last line; { "Conditional flow" at L.c + (0, 0.1) }
move
MessageFlow(right 2); L: last line; { "Message flow" at L.c + (0, 0.1) }
----

=== Pools and Lanes

[dpic,lanes,pdfwidth="90%",align="center"]
----
copy "bpmn.pic"

down

box width 10 height 0 with .nw at (0, 0) invisible 

Pool1: Pool(10, 2, []) ; Text("Pool", Pool1.Label.c, -90)

move

Pool2: Pool(10, 3, [
    Lane1: Lane(1, [])
    Lane2: Lane(1, [])
    Lane3: Lane(1, [])
])

Text("Pool with lanes", Pool2.Label.c, -90)
Text("Lane 1", Pool2.Lanes.Lane1.Label.c, -90)
Text("Lane 2", Pool2.Lanes.Lane2.Label.c, -90)
Text("Lane 3", Pool2.Lanes.Lane3.Label.c, -90)
----

<<<

== Example

[dpic,example1,align="center"]
----
copy "bpmn.pic"

down

DSP: [
    HorizontalBlackBoxPool(10, 0.5, "Delivery Service Provider")
] with .nw at (0, 0)

move

InventoryPool: Pool(10, 1.5, []) ; { Text("Inventory", InventoryPool.Label.c, -90) }
OrdersPool:    Pool(10, 1.5, []) ; { Text("Orders", OrdersPool.Label.c, -90) }
PaymentsPool:  Pool(10, 2, [])   ; { Text("Payments", PaymentsPool.Label.c, -90) }

Orders: [
    right
    Start(none); SequenceFlow()
    CreateOrder: Task("Create" "order"); SequenceFlow()
    OrderCreated: Throwing(message); SequenceFlow()
    PaymentCaptured: Catching(message); SequenceFlow()
    ShipOrder: Task("Ship" "order"); SequenceFlow()
    OrderDelivered: Catching(message); SequenceFlow()
    CloseOrder: Task("Close" "order"); SequenceFlow()
    End(message)
    down
] with .w at OrdersPool.Content.w + (0.5, 0)

Inventory: [
    right
    OrderCreated: Start(message);
    SequenceFlow();
    ReserveStock: Task("Reserve" "stock")
    SequenceFlow(0.9);
    StockReserved: Throwing(message); SequenceFlow()
    OrderClosed: Catching(message); SequenceFlow()
    DeductFromStock: Task("Deduct from" "stock"); SequenceFlow()
    End(none)
    down
] with .w at (Orders.OrderCreated.w.x, InventoryPool.Content.w.y)

Payments: [
    right
    OrderCreated: Start(message)
    SequenceFlow()
    RequestPaymentGateway: bpmn_gateway_parallel()
    move to (RequestPaymentGateway.w.x, RequestPaymentGateway.n.y + 0.7)
    StockReserved: Start(message)
    SequenceFlow(from StockReserved.s to RequestPaymentGateway.n)
    SequenceFlow(from RequestPaymentGateway.e right)
    RequestPayment: Task("Request" "payment")
    SequenceFlow()
    PaymentInitiated: Catching(message)
    SequenceFlow()
    CapturePayment: Task("Capture" "payment")
    SequenceFlow()
    PaymentCompleted: End(message)
    down
] with .w at  (Orders.OrderCreated.w.x, PaymentsPool.Content.w.y)

PSP: [
    HorizontalBlackBoxPool(10, 0.5, "Payment Service Provider")
] with .nw at PaymentsPool.sw - (0, 0.5)

MessageFlow(from Orders.OrderCreated.n to Inventory.OrderCreated.s)
MessageFlow(from Orders.OrderCreated.s to Payments.OrderCreated.n)

MessageFlow(from Inventory.StockReserved.s \
        to (Inventory.StockReserved.c.x, Payments.StockReserved.c.y),
        to Payments.StockReserved.e)

MessageFlow(from Payments.RequestPayment.s to (Payments.RequestPayment.s.x, PSP.n.y))
MessageFlow(from (Payments.PaymentInitiated.s.x, PSP.n.y) to Payments.PaymentInitiated.s)
MessageFlow(from Payments.CapturePayment.s to (Payments.CapturePayment.s.x, PSP.n.y))

MessageFlow(from Orders.ShipOrder.n to (Orders.ShipOrder.n.x, DSP.s.y))
MessageFlow(from (Orders.OrderDelivered.n.x, DSP.s.y) to Orders.OrderDelivered.n)

----

