:icons: font
:icon-set: fa
:hardbreaks:
:imagesdir: img
:source-highlighter: pygments
:data-uri:
:!figure-caption:

= bpmn.pic

`bpmn.pic` is a collection of https://gitlab.com/aplevich/dpic[DPIC] macros for generating BPMN 2.0 diagram images for use in various kinds of documents and presentations.

Although the library focuses on supporting SVG as the primary output format, most of the elements (except pools and lanes) should also work with other DPIC formats.

Currently supported BPMN element types include:

* **Events**: start, non-interrupting, catching, boundary, throwing, end;
* **Tasks**: none, receive, send, manual, service, user, script, rule;
* **Sub-Processes**: collapsed, sequential, parallel, loop, compensation, ad-hoc, expanded;
* **Gateways**: none, exclusive, parallel, inclusive, event-based (exclusive, parallel);
* **Flows**: sequence flow, default condition flow, conditional flow, message flow;
* **Pools**: horizontal pools and lanes, horizontal black box pools.

NOTE: The goal of `bpmn.pic` is to provide just the visual layer of BPMN 2.0. If you need full support for BPMN 2.0-compatible XML, please try other tools (like https://bpmn.io[bpmn.io]) instead.

== Resources

* https://gitlab.com/aplevich/dpic/-/blob/master/dpic-doc.pdf[DPIC documentation]

== Installation

Download `bpmn.pic` from https://gitlab.com/pkierat/bpmn-pic[here]:

----
$ wget https://gitlab.com/pkierat/bpmn-pic/-/raw/master/bpmn.pic
----

The file is self-contained, and has no external run-time dependencies apart from DPIC itself.

== Building from source

Buiding `bpmn.pic` requires the following tools to be available on the `PATH`:

* https://www.gnu.org/software/binutils/[Binutils]
* https://www.gnu.org/software/make/[Make]
* https://www.gnu.org/software/make/[M4 Macro Processor]

Building `README.pdf` requires in addition:

* DPIC
* Asciidoctor PDF
* Asciidoctor Diagram

**Procedure**:

. Clone the repository:
+
----
$ git clone git@gitlab.com:pkierat/bpmn-pic.git ./bpmn-pic
$ cd bpmn-pic
----
+
. Build `bpmn.pic`:
+
----
$ make -C src bpmn.pic
----
+
. (Optional) Build `README.pdf`:
+
----
$ make README.pdf
----

== Usage

. Include the `bpmn.pic` file in your PIC diagram using the `copy` statement:
+
[source, pic]
----
.PS
copy "bpmn.pic"

Start(none); SequenceFlow(); Task("Task"); SequenceFlow(); End(none)
.PE
----
+
. Generate the SVG file:
+
----
$ dpic -v diagram.pic > diagram.svg
----

The output SVG should look like below:

image::diagram.svg[align="center"]

<<<

== Macros

=== Events

`Start(type [, attributes ])`
`StartNonInterrupting(type [, attributes])`
`Boundary(type [, attributes])`
`BoundaryNonInterrupting(type [, attributes])`
`Catching(type [, attributes])`
`Throwing(type [, attributes])`
`End(type [, attributes])`

=== Gateways

`Gateway(type [, attributes ])`

=== Activities

`Task(text [, type [, attributes ] ])`
`SubProcess(text [, type [, attributes ] ])`

=== Flows

`SequenceFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`DefaultFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`ConditionalFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`
`MessageFlow([ linespec_1 [, linespec_2 [, ... ] ] ])`

=== Pools and lanes

`HorizontalPool(width, height, lanes [, attributes ])`
`HorizontalBlackBoxPool(width, height [, text [, attributes ] ])`
`HorizontalLane(height, process [, attributes ])`
`Pool(width, height, lanes [, attributes ])`
`Lane(height, process [, attributes ])`

=== Other

`Text(text, position [, rotation ])`

<<<

== Elements

=== Events

image::events.svg[pdfwidth="90%",align="center"]

<<<

=== Gateways

image::gateways.svg[pdfwidth="90%",align="center"]

=== Activities

==== Tasks

image::tasks.svg[pdfwidth="90%",align="center"]

==== Sub-processes

image::sub-processes.svg[pdfwidth="90%",align="center"]

==== Flows

image::flows.svg[pdfwidth="90%",align="center"]

=== Pools and Lanes

image::pools.svg[pdfwidth="90%",align="center"]

== Example

image::example.svg[pdfwidth="90%",align="center"]

